version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo node version check
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd my-vue-repo
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo post Building
      - aws s3 sync ./my-vue-repo/dist s3://webserver-bucket-kdt014 --delete
