pipeline {
    agent any

    environment {
        S3_BUCKET = 'webserver-bucket-kdt014'
        AWS_DEFAULT_REGION = 'ap-northeast-2'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-token',
                    url: 'https://github.com/costRider/cicd-study.git',
                    branch: 'main'
            }
        }

        stage('Install & Build') {
            steps {
                dir('my-vue-repo') {
                    nodejs(nodeJSInstallationName: 'nodejs22') {
                        sh 'node -v'
                        sh 'npm -v'
                        sh 'npm install'
                        sh 'npm run build'
                    }
                }
            }
        }

        stage('Deploy to S3') {
            steps {
                dir('my-vue-repo') {
                    sh "aws s3 sync ./dist s3://${S3_BUCKET} --delete"
                }
            }
        }
    }

    post {
        success {
            echo 'S3 배포 완료!'
        }
        failure {
            echo '빌드 실패'
        }
    }
}
